# Generated by Django 6.0.2 on 2026-03-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adminIds', models.ManyToManyField(related_name='admin_project', to='teams_management.userprofile')),
                ('memberIds', models.ManyToManyField(related_name='member_project', to='teams_management.userprofile')),
                ('teamIds', models.ManyToManyField(related_name='projects', to='teams_management.team')),
                ('users', models.ManyToManyField(related_name='projects', to='teams_management.userprofile')),
            ],
        ),
    ]
