# Generated by Django 6.0.2 on 2026-03-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_management', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='secret',
        ),
    ]
