# Generated by Django 6.0.2 on 2026-03-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_management', '0004_alter_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='adminIds',
            new_name='admins',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='memberIds',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='teamIds',
            new_name='teams',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
