# Generated by Django 6.0.2 on 2026-03-18 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_management', '0005_rename_adminids_project_admins_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in-progress', 'Inprogress')], default='todo', max_length=12)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignedUser', models.ManyToManyField(related_name='assigned_user_tasks', to='teams_management.userprofile')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='teams_management.project')),
            ],
        ),
    ]
