# Generated by Django 6.0.2 on 2026-03-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_management', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignedUser',
            new_name='assigned_user',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='teams_management.project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in-progress', 'In Progress')], default='todo', max_length=12),
        ),
    ]
